WIP: Add Django Rest Framework
sourcelair/bouncer-api pull request #27
Opened 2018-08-06 09:07 UTC by nzisouli

Add Django Rest Framework to the project and create a view that when hit, will return a JSON response. Closes #23

2018-08-07 09:16 UTC, nzisouli commented
Finish work

2018-08-07 11:11 UTC, akalipetis requested changes
Nice start! 👍 

I have added some first comments, also you need to lock your dependencies again.

Please add `pipenv install --dev --system --deploy` to Travis to avoid such issues in the future.

2018-08-07 11:11 UTC, akalipetis commented on bouncer/blacklist/tests.py
> +from rest_framework.response import Response
I think this is not needed here.

2018-08-07 11:11 UTC, akalipetis commented on bouncer/blacklist/urls.py
> +from django.urls import path, include
`include` is not used, please remove it.

2018-08-07 11:11 UTC, akalipetis commented on bouncer/blacklist/urls.py
> +from rest_framework import routers
`routers` are not used, please remove it.

2018-08-07 11:11 UTC, akalipetis commented on bouncer/blacklist/views.py
> +        print("GET METHOD")
Please remove `print` statement.

2018-08-07 11:11 UTC, akalipetis commented on bouncer/blacklist/views.py
> +            result = False
This could just be `result = is_email...`

2018-08-07 11:11 UTC, akalipetis commented on bouncer/blacklist/views.py
> +    @classmethod
Is this needed here?

2018-08-07 12:11 UTC, akalipetis requested changes
One more minor change.

2018-08-07 12:11 UTC, akalipetis commented on bouncer/blacklist/views.py
>      def get_extra_actions(cls):
Why do you need to define this method?

2018-08-14 06:50 UTC, akalipetis approved these changes
LGTM 🐻

2018-08-14 06:50 UTC, merged